### ISSUE TITLE
Proxy settings 

### ISSUE THREAD

**Issue by advancedeng** [jigsawsecurity/misp-client-windows#2]
Hi again,

It would be also ideal some proxy options to be provided.

Cheers,
Andreas

**Comment by jigsawsecurity** [comment]
I can add that. I will post an update here.

**Comment by jigsawsecurity** [comment]
I added proxy support to the application. It only supports socks proxy. 

Edit the settings.ini file to activate

Set proxy=1 to turn on the feature. I am not able to test because I do not have a proxy server. Please let me know if you have any issues with it. 

0 - specifies SOCKS Version 4
1 - specifies SOCKS Version 4A
2 - specifies SOCKS Version 5

**Comment by jigsawsecurity** [comment]
As no response I am closing issue. If there are any problems with using a proxy please let me know.

**Comment by advancedeng** [comment]
Thanks a lot Jigsaw! My plan is to test it and I will let you know!

Cheers,
Andreas
